CREATE OR REPLACE PACKAGE BODY XX_TEST_ERP_MIGRATION_PKG
AS
    PROCEDURE LOG_IT (P_MESSAGE IN VARCHAR2)
    IS
    BEGIN
       DBMS_OUTPUT.PUT_LINE('Hello');
    END;
END XX_TEST_ERP_MIGRATION_PKG;
/